"""empty message

Revision ID: 52c4b7ddcf76
Revises: 159fa8532a4d
Create Date: 2023-12-12 08:57:31.714323

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '52c4b7ddcf76'
down_revision = '159fa8532a4d'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Track_id', table_name='Track')
    op.drop_index('ix_Track_title', table_name='Track')
    op.drop_table('Track')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Track',
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['User.id'], name='Track_created_by_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Track_pkey')
    )
    op.create_index('ix_Track_title', 'Track', ['title'], unique=False)
    op.create_index('ix_Track_id', 'Track', ['id'], unique=False)
    # ### end Alembic commands ###
