"""empty message

Revision ID: 6022916b89fb
Revises: 57d9cab4dbc0
Create Date: 2023-12-12 09:56:06.574988

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6022916b89fb'
down_revision = '57d9cab4dbc0'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Track_id', table_name='Track')
    op.drop_index('ix_Track_title', table_name='Track')
    op.drop_table('Track')
    op.drop_index('ix_Album_album_name', table_name='Album')
    op.drop_index('ix_Album_id', table_name='Album')
    op.drop_table('Album')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Album',
    sa.Column('album_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('artist', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['User.id'], name='Album_created_by_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Album_pkey')
    )
    op.create_index('ix_Album_id', 'Album', ['id'], unique=False)
    op.create_index('ix_Album_album_name', 'Album', ['album_name'], unique=False)
    op.create_table('Track',
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['User.id'], name='Track_created_by_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Track_pkey')
    )
    op.create_index('ix_Track_title', 'Track', ['title'], unique=False)
    op.create_index('ix_Track_id', 'Track', ['id'], unique=False)
    # ### end Alembic commands ###
